/* eslint-disable @stylistic/object-property-newline, @stylistic/quote-props */
import type { AdminUiLocale } from './i18n';

const en: Record<string, string> = {
  '唯一 ID': 'Unique ID', '文章 ID': 'Article ID', '角色档案 ID': 'Profile ID', '角色 ID': 'Character ID', '标签 ID': 'Tag ID', '分类 ID': 'Category ID', '友链 ID': 'Link ID', '按钮 ID': 'Button ID', '语言 ID': 'Language ID', '卡片 ID': 'Card ID', '差分 ID': 'Variant ID', '图片 ID': 'Image ID',
  '隐藏此项': 'Hide item', '隐藏文章': 'Hide article', '名称': 'Name', '列表短名称': 'Short list name', '说明': 'Description', '作者／艺术家': 'Authors / artists', '作者': 'Author', '艺术家': 'Artist', '作者主页': 'Author links', '主页链接': 'Profile link', '链接地址': 'URL', '显示名称': 'Display name', '自定义图标': 'Custom icon',
  '图片': 'Image', '单张图片': 'Single image', '图片列表': 'Image list', '标签': 'Tags', '关联角色': 'Related characters', '创作日期': 'Creation date',
  '文章标题': 'Article title', '封面图片': 'Cover image', '文章分类': 'Article categories', '发布日期': 'Publication date', '正文': 'Content', '外部 Markdown 文件': 'External Markdown file', '摘要': 'Summary', '允许评论': 'Allow comments',
  '标题': 'Title', '内容': 'Content', '主题颜色': 'Theme color', '继承卡片 ID': 'Inherited card ID', '模板 ID': 'Template ID', '模板变量': 'Template variables', '变量名': 'Variable name', '变量值': 'Variable value', '信息卡片': 'Info card', '信息卡片模板': 'Info card templates', '卡片模板': 'Card template', '默认变量': 'Default variables', '默认值': 'Default value', '角色级信息卡片': 'Character info cards', '差分级信息卡片': 'Variant info cards', '图片级信息卡片': 'Image info cards',
  '角色名称': 'Character name', '角色差分': 'Character variants', '差分': 'Variant', '差分名称': 'Variant name', '差分图片': 'Variant images', '图片文件': 'Image file', '替代文本': 'Alt text', '角色索引': 'Character index', '角色': 'Character', '角色简介': 'Character description', '角色头像': 'Character avatar',
  '图库标签': 'Gallery tags', '标签名称': 'Tag name', '图标名称': 'Icon name', '受限标签': 'Restricted tag', '前置标签': 'Prerequisite tags', '分类': 'Category', '分类名称': 'Category name',
  '站点识别规则': 'Site recognition rules', '站点': 'Site', '域名': 'Domain', '中文名称': 'Chinese name', '英文名称': 'English name', '日文名称': 'Japanese name', '站点图标 URL': 'Site icon URL',
  '友链标签': 'Link tags', '友链分类': 'Link categories', '分类说明': 'Category description', '分类内友链': 'Links in category', '友链': 'Link', '站点名称': 'Site name', '站点地址': 'Site URL', '头像／Logo': 'Avatar / Logo', '简介': 'Description', '友链页显示设置': 'Links page display', '显示标签': 'Show tags', '显示简介': 'Show descriptions', '显示头像': 'Show avatars', '默认头像': 'Default avatar',
  '启用播放器': 'Enable player', '记忆并尝试自动播放': 'Remember and attempt autoplay', '默认音量': 'Default volume', '播放模式': 'Playback mode', '单曲循环': 'Repeat one', '列表顺序': 'Play in order', '列表随机': 'Shuffle', '曲目': 'Track', '曲名': 'Track title', '完整音频文件': 'Complete audio file', 'Intro + Loop 双文件': 'Separate Intro + Loop files', 'Intro 文件': 'Intro file', 'Loop 文件': 'Loop file', '专辑': 'Album', '封面图': 'Cover artwork', '封面规格': 'Artwork variant', '尺寸提示': 'Size hint', 'MIME 类型': 'MIME type', '循环区间': 'Loop range', '开始时间': 'Start time', '结束时间': 'End time',
  '站点标题': 'Site title', '版权信息': 'Copyright text', 'HTML 标题': 'HTML title', 'SEO 描述': 'SEO description', 'SEO 关键词': 'SEO keywords', '站点公开地址': 'Public site URL', '分享预览图': 'Share image', '浏览器主题色': 'Browser theme color', '浅色模式': 'Light mode', '深色模式': 'Dark mode',
  '头像': 'Avatar', '个人介绍段落': 'Introduction paragraphs', '段落': 'Paragraph', '社交链接': 'Social links', '链接': 'Link', '地址': 'URL', 'FontAwesome 图标': 'FontAwesome icon', '随机背景图': 'Random backgrounds', '首页操作按钮': 'Home actions', '按钮': 'Button', '按钮文本': 'Button text', '图标类名': 'Icon class', '链接类型': 'Link type', '站内路由': 'Internal route', '外部链接': 'External link', '目标地址': 'Target URL', '启用': 'Enabled', '链接动画间隔': 'Link animation interval', '按钮等待链接动画': 'Wait for link animation', '按钮初始延迟': 'Initial button delay', '按钮动画间隔': 'Button animation interval',
  '启用图库': 'Enable gallery', '启用文章': 'Enable articles', '启用友链': 'Enable links', '启用角色档案': 'Enable character profiles', '启用评论': 'Enable comments', '启用 Live2D': 'Enable Live2D', '图片查看器界面': 'Image viewer interface', '显示图库图片列表': 'Show gallery image list', '显示组内图片列表': 'Show group image list', '显示顶部标题': 'Show top title', '信息面板项目': 'Information panel fields', '日期': 'Date', '显示评论按钮': 'Show comments button',
  '回退语言': 'Fallback language', '默认语言': 'Default language', '语言列表': 'Languages', '语言': 'Language', '站点语言代码': 'Site language code', 'Giscus 语言代码': 'Giscus locale', '浏览器语言别名': 'Browser language aliases',
  '文章页信息卡片': 'Article page cards', '主题图片': 'Theme image', '浅色模式图片': 'Light theme image', '深色模式图片': 'Dark theme image',
  'GitHub 仓库': 'GitHub repository', '仓库 ID': 'Repository ID', 'Discussion 分类': 'Discussion category', '页面映射': 'Page mapping', '严格匹配': 'Strict matching', '是': 'Yes', '否': 'No', '启用反应': 'Enable reactions', '输出元数据': 'Emit metadata', '评论框位置': 'Comment box position', '顶部': 'Top', '底部': 'Bottom', '加载策略': 'Loading strategy', '懒加载': 'Lazy', '立即加载': 'Eager',
  '默认图标包': 'Default icon pack', '回退图标名称': 'Fallback icon', '模型': 'Model', '模型入口文件': 'Model entry file', '缩放倍率': 'Scale', 'X 偏移': 'X offset', 'Y 偏移': 'Y offset', '显示区域': 'Display area', '宽度': 'Width', '高度': 'Height', '停靠位置': 'Anchor', '水平偏移': 'Horizontal offset', '垂直偏移': 'Vertical offset', '透明度': 'Opacity', '交互': 'Interaction', '视角跟随鼠标': 'Track cursor', '点击切换表情': 'Change expression on click', '自动表情间隔': 'Automatic expression interval', '表情恢复延迟': 'Expression reset delay', '待机动作组': 'Idle motion group', 'Cubism 4 Core 运行时': 'Cubism 4 Core runtime', 'Cubism 2 运行时': 'Cubism 2 runtime',
  '可为各语言分别填写；留空的语言由站点回退策略处理。': 'Enter a value for each language; empty values use the site fallback policy.', '用于 URL 和配置引用，创建后尽量不要修改。': 'Used in URLs and configuration references. Avoid changing it after creation.', '正文与外部 Markdown 至少填写一项。支持富文本和 Markdown 源码双模式。': 'Provide inline content or an external Markdown file.', '使用英文逗号分隔。': 'Separate values with commas.',
  '仅允许字母、数字、点、下划线和连字符，且需以字母或数字开头。': 'Use letters, numbers, dots, underscores or hyphens, starting with a letter or number.', '使用双文件模式时填写；与完整音频文件二选一。': 'Use either separate Intro + Loop files or one complete audio file.', '例如 512x512。': 'For example, 512x512.', '例如 image/webp。': 'For example, image/webp.', '引用同一角色层级中已有的信息卡片 ID。': 'Reference an existing info card ID in this character hierarchy.', '引用当前角色 infoCardTemplates 中的模板 ID。': 'Reference a template ID from this character’s infoCardTemplates.', '格式应为 owner/repository。': 'Use the owner/repository format.', '秒': 'seconds', '请输入 URL、mailto: 或 tel: 地址。': 'Enter a URL, mailto: or tel: address.',
};

const jp: Record<string, string> = {
  ...en,
  '唯一 ID': '一意 ID', '文章 ID': '記事 ID', '角色档案 ID': '資料 ID', '角色 ID': 'キャラクター ID', '标签 ID': 'タグ ID', '分类 ID': 'カテゴリ ID', '友链 ID': 'リンク ID', '按钮 ID': 'ボタン ID', '语言 ID': '言語 ID', '卡片 ID': 'カード ID', '差分 ID': '差分 ID', '图片 ID': '画像 ID',
  '隐藏此项': 'この項目を非表示', '隐藏文章': '記事を非表示', '名称': '名前', '列表短名称': '一覧用の短い名前', '说明': '説明', '作者／艺术家': '作者／アーティスト', '作者': '作者', '艺术家': 'アーティスト', '作者主页': '作者リンク', '主页链接': 'プロフィールリンク', '链接地址': 'URL', '显示名称': '表示名', '自定义图标': 'カスタムアイコン',
  '图片': '画像', '单张图片': '単一画像', '图片列表': '画像一覧', '标签': 'タグ', '关联角色': '関連キャラクター', '创作日期': '制作日',
  '文章标题': '記事タイトル', '封面图片': 'カバー画像', '文章分类': '記事カテゴリ', '发布日期': '公開日', '正文': '本文', '外部 Markdown 文件': '外部 Markdown ファイル', '摘要': '要約', '允许评论': 'コメントを許可',
  '标题': 'タイトル', '内容': '内容', '主题颜色': 'テーマ色', '继承卡片 ID': '継承元カード ID', '模板 ID': 'テンプレート ID', '模板变量': 'テンプレート変数', '变量名': '変数名', '变量值': '変数値', '信息卡片': '情報カード', '信息卡片模板': '情報カードテンプレート', '卡片模板': 'カードテンプレート', '默认变量': '既定の変数', '默认值': '既定値', '角色级信息卡片': 'キャラクター情報カード', '差分级信息卡片': '差分情報カード', '图片级信息卡片': '画像情報カード',
  '角色名称': 'キャラクター名', '角色差分': 'キャラクター差分', '差分': '差分', '差分名称': '差分名', '差分图片': '差分画像', '图片文件': '画像ファイル', '替代文本': '代替テキスト', '角色索引': 'キャラクター索引', '角色': 'キャラクター', '角色简介': 'キャラクター紹介', '角色头像': 'キャラクターアイコン',
  '图库标签': 'ギャラリータグ', '标签名称': 'タグ名', '图标名称': 'アイコン名', '受限标签': '制限付きタグ', '前置标签': '前提タグ', '分类': 'カテゴリ', '分类名称': 'カテゴリ名',
  '站点识别规则': 'サイト識別規則', '站点': 'サイト', '域名': 'ドメイン', '中文名称': '中国語名', '英文名称': '英語名', '日文名称': '日本語名', '站点图标 URL': 'サイトアイコン URL',
  '友链标签': 'リンクタグ', '友链分类': 'リンクカテゴリ', '分类说明': 'カテゴリ説明', '分类内友链': 'カテゴリ内リンク', '友链': 'リンク', '站点名称': 'サイト名', '站点地址': 'サイト URL', '头像／Logo': 'アバター／ロゴ', '简介': '紹介', '友链页显示设置': 'リンクページ表示', '显示标签': 'タグを表示', '显示简介': '紹介を表示', '显示头像': 'アバターを表示', '默认头像': '既定のアバター',
  '启用播放器': 'プレイヤーを有効化', '记忆并尝试自动播放': '設定を記憶して自動再生を試す', '默认音量': '既定音量', '播放模式': '再生モード', '单曲循环': '1曲リピート', '列表顺序': '順番に再生', '列表随机': 'シャッフル', '曲目': '曲', '曲名': '曲名', '完整音频文件': '完全な音声ファイル', 'Intro + Loop 双文件': 'Intro + Loop 分割ファイル', 'Intro 文件': 'Intro ファイル', 'Loop 文件': 'Loop ファイル', '专辑': 'アルバム', '封面图': 'カバーアート', '封面规格': 'カバー仕様', '尺寸提示': 'サイズ情報', 'MIME 类型': 'MIME タイプ', '循环区间': 'ループ区間', '开始时间': '開始時間', '结束时间': '終了時間',
  '站点标题': 'サイトタイトル', '版权信息': '著作権表記', 'HTML 标题': 'HTML タイトル', 'SEO 描述': 'SEO 説明', 'SEO 关键词': 'SEO キーワード', '站点公开地址': 'サイト公開 URL', '分享预览图': '共有プレビュー画像', '浏览器主题色': 'ブラウザーのテーマ色', '浅色模式': 'ライトモード', '深色模式': 'ダークモード',
  '头像': 'アバター', '个人介绍段落': '自己紹介段落', '段落': '段落', '社交链接': 'SNS リンク', '链接': 'リンク', '地址': 'URL', 'FontAwesome 图标': 'FontAwesome アイコン', '随机背景图': 'ランダム背景画像', '首页操作按钮': 'ホーム操作ボタン', '按钮': 'ボタン', '按钮文本': 'ボタンの文言', '图标类名': 'アイコンクラス', '链接类型': 'リンク種別', '站内路由': '内部ルート', '外部链接': '外部リンク', '目标地址': '移動先 URL', '启用': '有効', '链接动画间隔': 'リンクアニメーション間隔', '按钮等待链接动画': 'リンクアニメーションを待つ', '按钮初始延迟': 'ボタン初期遅延', '按钮动画间隔': 'ボタンアニメーション間隔',
  '启用图库': 'ギャラリーを有効化', '启用文章': '記事を有効化', '启用友链': 'リンクを有効化', '启用角色档案': 'キャラクター資料を有効化', '启用评论': 'コメントを有効化', '启用 Live2D': 'Live2D を有効化', '图片查看器界面': '画像ビューアー UI', '显示图库图片列表': 'ギャラリー画像一覧を表示', '显示组内图片列表': 'グループ内画像一覧を表示', '显示顶部标题': '上部タイトルを表示', '信息面板项目': '情報パネル項目', '日期': '日付', '显示评论按钮': 'コメントボタンを表示',
  '回退语言': 'フォールバック言語', '默认语言': '既定言語', '语言列表': '言語一覧', '语言': '言語', '站点语言代码': 'サイト言語コード', 'Giscus 语言代码': 'Giscus 言語コード', '浏览器语言别名': 'ブラウザー言語別名',
  '文章页信息卡片': '記事ページ情報カード', '主题图片': 'テーマ画像', '浅色模式图片': 'ライトモード画像', '深色模式图片': 'ダークモード画像',
  'GitHub 仓库': 'GitHub リポジトリ', '仓库 ID': 'リポジトリ ID', 'Discussion 分类': 'Discussion カテゴリ', '页面映射': 'ページ対応', '严格匹配': '厳密一致', '是': 'はい', '否': 'いいえ', '启用反应': 'リアクションを有効化', '输出元数据': 'メタデータを出力', '评论框位置': 'コメント欄の位置', '顶部': '上', '底部': '下', '加载策略': '読み込み方法', '懒加载': '遅延読み込み', '立即加载': '即時読み込み',
  '默认图标包': '既定アイコンパック', '回退图标名称': 'フォールバックアイコン', '模型': 'モデル', '模型入口文件': 'モデル入口ファイル', '缩放倍率': '拡大率', 'X 偏移': 'X オフセット', 'Y 偏移': 'Y オフセット', '显示区域': '表示領域', '宽度': '幅', '高度': '高さ', '停靠位置': '固定位置', '水平偏移': '水平オフセット', '垂直偏移': '垂直オフセット', '透明度': '不透明度', '交互': '操作', '视角跟随鼠标': '視線をマウスに追従', '点击切换表情': 'クリックで表情変更', '自动表情间隔': '自動表情間隔', '表情恢复延迟': '表情リセット遅延', '待机动作组': '待機モーショングループ', 'Cubism 4 Core 运行时': 'Cubism 4 Core ランタイム', 'Cubism 2 运行时': 'Cubism 2 ランタイム',
  '可为各语言分别填写；留空的语言由站点回退策略处理。': '言語ごとに入力できます。空欄はサイトのフォールバック設定を使用します。', '用于 URL 和配置引用，创建后尽量不要修改。': 'URL と設定参照に使用します。作成後の変更は避けてください。', '正文与外部 Markdown 至少填写一项。支持富文本和 Markdown 源码双模式。': '本文または外部 Markdown ファイルのどちらかを入力してください。', '使用英文逗号分隔。': 'カンマで区切ってください。',
  '仅允许字母、数字、点、下划线和连字符，且需以字母或数字开头。': '英数字、ピリオド、アンダースコア、ハイフンを使用し、英数字で始めてください。', '使用双文件模式时填写；与完整音频文件二选一。': 'Intro + Loop の分割ファイルか、完全な音声ファイルのどちらかを使用します。', '例如 512x512。': '例: 512x512。', '例如 image/webp。': '例: image/webp。', '引用同一角色层级中已有的信息卡片 ID。': '同じキャラクター階層にある既存の情報カード ID を参照します。', '引用当前角色 infoCardTemplates 中的模板 ID。': '現在のキャラクターの infoCardTemplates にあるテンプレート ID を参照します。', '格式应为 owner/repository。': 'owner/repository 形式で入力してください。', '秒': '秒', '请输入 URL、mailto: 或 tel: 地址。': 'URL、mailto:、tel: のいずれかを入力してください。',
};

export const translateDefinition = (value: string | undefined, locale: AdminUiLocale): string => {
  if (!value || locale === 'zh') return value ?? '';
  return (locale === 'jp' ? jp : en)[value] ?? value;
};
