import { bgmFields, linksFields } from './content-fields';
import {
  articleCategoriesField,
  articleFields,
  characterListField,
  characterProfileFields,
  imageFields,
  siteRegistryField,
  tagListField,
} from './fields';
import {
  appFields,
  articlesPageFields,
  featureFields,
  fontAwesomeFields,
  giscusFields,
  htmlFields,
  languageFields,
  live2dEngineFields,
  live2dFields,
  personalFields,
} from './settings-fields';
import type { AdminResource, AdminSection } from './types';

const resource = (value: AdminResource): AdminResource => value;

export const adminSections: AdminSection[] = [
  {
    id: 'content',
    label: '内容管理',
    icon: 'LibraryBig',
    resources: [
      resource({
        id: 'gallery',
        label: '图库作品',
        singular: '作品',
        description: '作品、图片组、作者、标签与角色关联。',
        icon: 'Images',
        kind: 'collection',
        path: 'src/config/images',
        codec: 'image',
        fields: imageFields,
        previewPath: '/#/gallery/{id}',
      }),
      resource({
        id: 'articles',
        label: '文章',
        singular: '文章',
        description: '正文、分类、封面、发布日期和评论设置。',
        icon: 'FileText',
        kind: 'collection',
        path: 'src/config/articles',
        codec: 'article',
        fields: articleFields,
        previewPath: '/#/articles/{id}',
      }),
      resource({
        id: 'profiles',
        label: '角色档案',
        singular: '角色档案',
        description: '角色、差分、立绘和信息卡片的正式层级。',
        icon: 'ContactRound',
        kind: 'collection',
        path: 'src/config/character-profiles',
        codec: 'characterProfile',
        fields: characterProfileFields,
        previewPath: '/#/character-profiles/{id}',
      }),
    ],
  },
  {
    id: 'structure',
    label: '结构与关系',
    icon: 'Network',
    resources: [
      resource({
        id: 'characters',
        label: '角色索引',
        description: '图库与档案共用的角色字典。',
        icon: 'UsersRound',
        kind: 'file',
        path: 'src/config/characters.json5',
        codec: 'characters',
        fields: [characterListField],
      }),
      resource({
        id: 'tags',
        label: '图库标签',
        description: '含前置关系和受限标记的标签体系。',
        icon: 'Tags',
        kind: 'file',
        path: 'src/config/tags.json5',
        codec: 'tags',
        fields: [tagListField],
      }),
      resource({
        id: 'articleCategories',
        label: '文章分类',
        description: '文章使用的正式分类字典。',
        icon: 'FolderTree',
        kind: 'file',
        path: 'src/config/articles-categories.json5',
        codec: 'articleCategories',
        fields: [articleCategoriesField],
      }),
      resource({
        id: 'links',
        label: '友链体系',
        description: '友链标签、分类、站点和页面显示规则。',
        icon: 'Link2',
        kind: 'file',
        path: 'src/config/links.json5',
        codec: 'links',
        fields: linksFields,
      }),
    ],
  },
  {
    id: 'presentation',
    label: '站点呈现',
    icon: 'PanelsTopLeft',
    resources: [
      resource({
        id: 'personal',
        label: '首页与个人资料',
        description: '头像、介绍、社交链接、背景和操作按钮。',
        icon: 'House',
        kind: 'file',
        path: 'src/config/personal.json5',
        codec: 'personal',
        fields: personalFields,
      }),
      resource({
        id: 'app',
        label: '站点名称与版权',
        description: '页面标题和页脚版权文本。',
        icon: 'BadgeInfo',
        kind: 'file',
        path: 'src/config/app.json5',
        codec: 'app',
        fields: appFields,
      }),
      resource({
        id: 'html',
        label: 'SEO 与浏览器',
        description: 'Meta、站点地址、主题色和图标。',
        icon: 'SearchCheck',
        kind: 'file',
        path: 'src/config/html.json5',
        codec: 'default',
        fields: htmlFields,
      }),
      resource({
        id: 'languages',
        label: '语言与回退',
        description: '启用语言、默认语言和浏览器别名。',
        icon: 'Languages',
        kind: 'file',
        path: 'src/config/languages.json5',
        codec: 'languages',
        fields: languageFields,
      }),
      resource({
        id: 'articlesPage',
        label: '文章页卡片',
        description: '文章页面顶部的信息卡片。',
        icon: 'LayoutDashboard',
        kind: 'file',
        path: 'src/config/articles-page.json5',
        codec: 'articlesPage',
        fields: articlesPageFields,
      }),
    ],
  },
  {
    id: 'experience',
    label: '功能与体验',
    icon: 'Sparkles',
    resources: [
      resource({
        id: 'features',
        label: '功能开关',
        description: '站点模块和图片查看器界面。',
        icon: 'SlidersHorizontal',
        kind: 'file',
        path: 'src/config/features.json5',
        codec: 'default',
        fields: featureFields,
      }),
      resource({
        id: 'bgm',
        label: '背景音乐',
        description: '播放器行为、曲目、封面和循环区间。',
        icon: 'AudioLines',
        kind: 'file',
        path: 'src/config/bgm.json5',
        codec: 'bgm',
        fields: bgmFields,
      }),
      resource({
        id: 'live2d',
        label: 'Live2D 挂件',
        description: '模型、画布位置和交互行为。',
        icon: 'PersonStanding',
        kind: 'file',
        path: 'src/config/live2d.json5',
        codec: 'default',
        fields: live2dFields,
      }),
      resource({
        id: 'live2dEngine',
        label: 'Live2D 运行时',
        description: 'Cubism Core 运行时文件。',
        icon: 'Cpu',
        kind: 'file',
        path: 'src/config/live2d-engine.json5',
        codec: 'default',
        fields: live2dEngineFields,
      }),
    ],
  },
  {
    id: 'integrations',
    label: '外部集成',
    icon: 'PlugZap',
    resources: [
      resource({
        id: 'giscus',
        label: 'Giscus 评论',
        description: '仓库、Discussion 分类和加载策略。',
        icon: 'MessagesSquare',
        kind: 'file',
        path: 'src/config/giscus.json5',
        codec: 'default',
        fields: giscusFields,
      }),
      resource({
        id: 'fontawesome',
        label: 'FontAwesome',
        description: '默认图标包与回退图标。',
        icon: 'Shapes',
        kind: 'file',
        path: 'src/config/fontawesome.json5',
        codec: 'default',
        fields: fontAwesomeFields,
      }),
      resource({
        id: 'sites',
        label: '站点识别规则',
        description: '外部域名的显示名称和图标映射。',
        icon: 'Globe2',
        kind: 'file',
        path: 'src/config/sites.json5',
        codec: 'sites',
        fields: [siteRegistryField],
      }),
    ],
  },
];

export const adminResources = adminSections.flatMap(section => section.resources);

export const getAdminResource = (id: string): AdminResource | undefined => (
  adminResources.find(item => item.id === id)
);
